# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10, dtype = 'int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

#### Create an array of 10 ones

In [4]:
np.ones(10, dtype = 'int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

#### Create an array of 10 fives

In [11]:
np1 = np.ones(10, dtype = 'int64')
np2 = 5*np1;
np2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

#### Create an array of the integers from 10 to 50

In [14]:
np.arange(10,51)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [16]:
np.eye(3, dtype = 'int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### Use NumPy to generate a random number between 0 and 1

In [17]:
np.random.rand()

0.4242448189721284

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [18]:
np.random.randn(25)

array([ 1.56969034, -0.18443096,  1.31053119,  1.47331587,  0.80479887,
       -0.39852371, -0.65693652,  2.50073   , -0.10667877, -0.09656914,
       -1.13624438,  0.05010631, -2.27474176, -0.28120171,  0.34839509,
       -0.81760827,  0.01830422,  1.18226565, -2.05069385, -0.97813191,
       -0.6154581 ,  1.52075779,  0.81966537, -1.35550716, -0.50810821])

#### Create the following matrix:

In [64]:
arr = np.arange(1,26)
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [19]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Now do the following

#### Get the sum of all the values in mat

In [20]:
mat = ([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
sum = np.sum(mat)
sum

325

#### Get the standard deviation of the values in mat

In [21]:
std = np.std(mat)
std

7.211102550927978

#### Get the sum of all the columns in mat

In [22]:
sum_of_columns = np.sum(mat,axis = 0)
sum_of_columns 

array([ 15,  40,  65,  90, 115])